---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: include configuration file
    include_vars: ansible.cfg

  - name: set timezone to {{timezone}}
    command: timedatectl set-timezone {{timezone}}

  - name: install aptitude
    apt: name=aptitude state=latest

  - name: apt upgrade
    apt: upgrade=full

  - name: install tools
    apt: name={{item}} state=latest
    with_items:
      - openssh-server

  - name: install tools for docker
    apt: name={{item}} state=latest
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: add Docker GPG Key
    apt_key: url="https://download.docker.com/linux/ubuntu/gpg" state=present

  - name: add Docker Repository
    command: add-apt-repository "deb [arch={{system_architecture}}] https://download.docker.com/linux/ubuntu xenial stable"

  - name: install docker-ce
    apt:
      name: docker-ce
      update_cache: yes
