---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    timezone: 'Europe/Berlin'
    system_architecture: 'amd64'  #docker supports: amd64, armhf
    host_name: 'raspberry-shadow'
  roles:
      - basic-system-configuration
      - openssh-server
      - docker-ce
